### ISSUE TITLE
2.2 Ensure that sinks are configured for all log entries - problem with multiple projects in an aggregator

### ISSUE THREAD

**Issue by M0nsieurChat** [turbot/steampipe-mod-gcp-compliance#110]
**Describe the bug**
When using this dashboard against an aggregator returning a set of GCP projects, only the last project will return a correctly configured log sink although every other one is configured the same (using terraform)
![image](https://github.com/turbot/steampipe-mod-gcp-compliance/assets/4733617/e3cc6774-5f94-4023-a4f8-3b98c3626294)

I will post a MR to update the query so that it successfully works for all projects with a correctly configured sink.
![image](https://github.com/turbot/steampipe-mod-gcp-compliance/assets/4733617/4d724d1e-7f68-435a-b289-f12512bebecd)

**Steampipe version (`steampipe -v`)**
steampipe 0.20.9

**Plugin version (`steampipe plugin list`)**
gcp: 0.41.0

**To reproduce**
Use this dashboard against an aggregator or put multiple gcp project in the search-path

**Expected behavior**
For every project in the search-path (or aggregator), all projects with correctly configured log sinks should return as OK

**Comment by M0nsieurChat** [comment]
Here is the PR : https://github.com/turbot/steampipe-mod-gcp-compliance/pull/111

**Comment by rajlearner17** [comment]
@M0nsieurChat, Thanks for using Steampipe!

Nice catch on this; I appreciate raising PR for this as well 👍 

Just adding this image to track and explain how the query behaved differently. Not sure even why we might have used this `string_agg`. Anyways, we will go ahead and approve the PR

![image](https://github.com/turbot/steampipe-mod-gcp-compliance/assets/26873346/a57c5403-3a98-478d-be59-066df8889a88)
After the fix

![image](https://github.com/turbot/steampipe-mod-gcp-compliance/assets/26873346/218ae8ee-7dcf-4071-802b-52770f6b9a1d)

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/steampipe-mod-gcp-compliance/pull/111 !!

Thanks @M0nsieurChat for the fix 👍.
