### ISSUE TITLE
Create queries for GKE CIS v1.3.0

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-mod-gcp-compliance#123]
See discussion in https://github.com/turbot/steampipe-mod-gcp-compliance/pull/117 (moving to issue so the information in the PR isn't lost)

**Comment by saisirishreddy** [comment]
I agree that referencing to the Kubernetes mod where applicable helps along with the Corresponding Cloud queries. However I think handling the config files might be challenging as the access requirements are not the same.

**Comment by cbruno10** [comment]
@saisirishreddy I think we can start off with GCP specific queries in the GKE CIS mod, so a user would only need to setup the GCP plugin connections. We can also add the Kubernetes queries, and then if a user sets up a Kubernetes plugin connection (or multiple), those Kubernetes controls will run; else, those controls will have no results.

**Comment by saisirishreddy** [comment]
@cbruno10  would GKE CIS be a new mod..? or a subset in [steampipe-mod-gcp-compliance](https://github.com/turbot/steampipe-mod-gcp-compliance).
