### ISSUE TITLE
Controls between 2.6 and 2.9 of CIS v2.0.0 doesn't work with the GCP project configured as the instruction in the documantation.

### ISSUE THREAD

**Issue by k-kawa** [turbot/steampipe-mod-gcp-compliance#150]
Controls between 2.6 and 2.9 of CIS v2.0.0 report alert on the GCP projects even after they are configured as the `Remediation` section say.

- https://hub.steampipe.io/mods/turbot/gcp_compliance/controls/control.cis_v200_2_6
- https://hub.steampipe.io/mods/turbot/gcp_compliance/controls/control.cis_v200_2_7
- https://hub.steampipe.io/mods/turbot/gcp_compliance/controls/control.cis_v200_2_8
- https://hub.steampipe.io/mods/turbot/gcp_compliance/controls/control.cis_v200_2_9

The reason is that Logging Query Language written in their documentation has `(` and `)` but the queries used by their Control don't care them.

I think that this is a bug of Queries and the documentations look correct.

**Comment by khushboo9024** [comment]
Hi @k-kawa Sorry for the delay, and thank you for raising this issue. We will investigate it and update you as soon as possible.

**Comment by khushboo9024** [comment]
Resolved in https://github.com/turbot/steampipe-mod-gcp-compliance/pull/154
