### ISSUE TITLE
The query 'kms_key_users_limited_to_3' fails due to hardcoded connection `gcp_parker`

### ISSUE THREAD

**Issue by ParthaI** [turbot/steampipe-mod-gcp-compliance#169]
**Describe the bug**
While running the control ` Ensure KMS encryption keys has three or less thab three number of users`  Encounter the error `ERROR: relation "gcp_parker.gcp_kms_key" does not exist (SQLSTATE 42P01)`

**Powerpipe version (`powerpipe -v`)**
Example: v0.3.0-alpha.202405082209

**Steampipe version (`steampipe -v`)**
Example: v0.23.2

**Plugin version (`steampipe plugin list`)**
Example: latest

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by khushboo9024** [comment]
Fixed in https://github.com/turbot/steampipe-mod-gcp-compliance/pull/170
