### ISSUE TITLE
Inconsistency in the Control Title Casing

### ISSUE THREAD

**Issue by ParthaI** [turbot/steampipe-mod-gcp-compliance#172]
**Describe the bug**

There is a mismatch in the control title casing. In some places, it is written as `Ensure that retention policies on` while in others it is `Ensure That Retention Policies on`. I don't know whether this inconsistency is intentional.

![Screenshot 2024-06-06 at 10 34 42 PM](https://github.com/turbot/steampipe-mod-gcp-compliance/assets/47887552/b3071d58-9cdf-46c7-b7db-6c835066866c)

**Powerpipe version (`powerpipe -v`)**
Example: v0.3.1

**Steampipe version (`steampipe -v`)**
Example: v0.23.2

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by khushboo9024** [comment]
@ParthaI These titles are as per the CIS document; hence, we are closing this issue.
