### ISSUE TITLE
kubernetes_cluster_private_cluster_config_enabled query is incorrect

### ISSUE THREAD

**Issue by bigdatasourav** [turbot/steampipe-mod-gcp-compliance#58]
**Describe the bug**
Control: Verify all GKE clusters are Private Clusters is about checking the clusters are private or not. However, in the query, if the cluster is private, it will show as an alarm.

**Comment by misraved** [comment]
closed in https://github.com/turbot/steampipe-mod-gcp-compliance/pull/59
