### ISSUE TITLE
Update benchmark and control tags for compatibility with dashboard page

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-mod-gcp-compliance#63]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cbruno10** [comment]
Closed in https://github.com/turbot/steampipe-mod-gcp-compliance/commit/668275b7807e76d67c0622ea3c7ae3bd59208dea
