### ISSUE TITLE
Add  GCP CIS 1.3  controls

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-mod-gcp-compliance#71]
**Is your feature request related to a problem? Please describe.**

[Reference](https://workbench.cisecurity.org/benchmarks/7203)

[CIS 1.3.0 milestone details](https://workbench.cisecurity.org/community/48/milestones/761)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

- [x] https://github.com/turbot/steampipe-mod-gcp-compliance/issues/73
- [x] https://github.com/turbot/steampipe-mod-gcp-compliance/issues/74
- [x] https://github.com/turbot/steampipe-mod-gcp-compliance/issues/75

**Comment by vkumbha** [comment]
GCP Compliance v0.11 released
