### ISSUE TITLE
Code tidy up e.g. use query = instead of sql = when connecting controls to queries across GCP compliance

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-mod-gcp-compliance#86]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by misraved** [comment]
Closed as a part of https://github.com/turbot/steampipe-mod-gcp-compliance/pull/87.

This enhancement is available in [v0.13](https://github.com/turbot/steampipe-mod-gcp-compliance/blob/main/CHANGELOG.md#v013-2023-01-20) plugin version.
